EventStream 报错问题
hyperf/engine pull request #30
Opened 2024-11-15 02:38 UTC by tw2066

Update EventStream.php 
https://github.com/hyperf/hyperf/issues/7154

2024-11-16 05:31 UTC, sy-records requested changes

2024-11-16 05:31 UTC, sy-records commented on src/Http/EventStream.php
>      }
这个修改不对吧。

返回`bool` return呢？

2024-11-16 07:21 UTC, mitoop commented on src/Http/EventStream.php
>      }
改这个地方不对 `prod.ERROR: Hyperf\Engine\Http\WritableConnection::end(): Return value must be of type bool, null returned[39]` 错误是这个
```php
    public function end(): bool
    {
        return $this->response->end();
    }
```
 是 Swoole\Http\Response@end 返回的不对 应该是bool 现在是null 但是的swoole ide helper提示的Swoole\Http\Response@end返回的确实是bool 是不是Swoole进行了破坏性调整? Swoole 版本 5.1.4

2024-11-16 07:46 UTC, mitoop commented on src/Http/EventStream.php
>      }
```php
<?php

declare(strict_types=1);
/**
 * This file is part of Hyperf.
 *
 * @link     https://www.hyperf.io
 * @document https://hyperf.wiki
 * @contact  group@hyperf.io
 * @license  https://github.com/hyperf/hyperf/blob/master/LICENSE
 */

namespace Hyperf\Engine\Http;

use Hyperf\Engine\Contract\Http\Writable;
use Swoole\Http\Response;

class WritableConnection implements Writable
{
    public function __construct(protected Response $response)
    {
    }

    public function write(string $data): bool
    {
        return $this->response->write($data);
    }

    /**
     * @return Response
     */
    public function getSocket(): mixed
    {
        return $this->response;
    }

    public function end(): bool
    {
        return $this->response->end(); // Swoole\Http\Response@end 方法返回的值发生了变化
    }
}
```

2024-11-18 02:25 UTC, assert6 commented
https://github.com/hyperf/engine/pull/31

2024-11-18 02:25 UTC, closed without merging